name: CI

on:
  push:
    branches:
      - "master"
      - "release/*"
  pull_request:
    branches:
      - "master"
      - "release/*"
  merge_group:
    types: [checks_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Syntax Checks

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          rustup set auto-self-update disable
          cargo install chewing-cli --git https://github.com/chewing/libchewing

      - name: Build
        run: |
          cmake -B build
          cmake --build build
